"""updated sybil clusters table with cluster_id as varchar

Revision ID: 165845e141af
Revises: 3abcd9c86cf8
Create Date: 2023-09-29 20:24:02.654926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165845e141af'
down_revision: Union[str, None] = '3abcd9c86cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sybil_clusters', 'cluster_id',
               existing_type=sa.INTEGER(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sybil_clusters', 'cluster_id',
               existing_type=sa.VARCHAR(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
