"""updated transaction table with processed column_

Revision ID: 16c26a925644
Revises: 3783d8886dde
Create Date: 2023-10-19 09:40:18.993388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c26a925644'
down_revision: Union[str, None] = '3783d8886dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactions')
    op.add_column('contract_transactions', sa.Column('processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_transactions', 'processed')
    op.create_table('interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='interactions_pkey')
    )
    # ### end Alembic commands ###
