"""updated transfer table with processed column_

Revision ID: 3783d8886dde
Revises: fa552a2a6b8e
Create Date: 2023-10-12 17:19:52.197335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3783d8886dde'
down_revision: Union[str, None] = 'fa552a2a6b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
