"""updated sybil clusters table with labels

Revision ID: 3f0ce6dc134f
Revises: 165845e141af
Create Date: 2023-10-05 15:16:01.992167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0ce6dc134f'
down_revision: Union[str, None] = '165845e141af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sybil_clusters', sa.Column('labels', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sybil_clusters', 'labels')
    # ### end Alembic commands ###
