"""added suspicious cluster table

Revision ID: 68e52046e5fb
Revises: 2dbd184f20e1
Create Date: 2023-09-17 13:49:56.432704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e52046e5fb'
down_revision: Union[str, None] = '2dbd184f20e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspicious_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'eoas', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eoas', type_='unique')
    op.drop_table('suspicious_clusters')
    # ### end Alembic commands ###
