"""updated chainId to SybilClusters

Revision ID: 924d86c3b2ae
Revises: b69f9c797d67
Create Date: 2023-11-09 19:59:29.354766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924d86c3b2ae'
down_revision: Union[str, None] = 'b69f9c797d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
