"""add contract transaction and refine tables

Revision ID: a3556e5718fb
Revises: 0a35cab561a6
Create Date: 2023-09-19 16:20:26.294762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3556e5718fb'
down_revision: Union[str, None] = '0a35cab561a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_transactions',
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('logs', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_transactions')
    # ### end Alembic commands ###
