"""Added chainId to SybilClusters

Revision ID: b69f9c797d67
Revises: cfc0f131048c
Create Date: 2023-11-09 19:48:30.886152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b69f9c797d67'
down_revision: Union[str, None] = 'cfc0f131048c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
