"""Added chainId to all tables

Revision ID: cfc0f131048c
Revises: 16c26a925644
Create Date: 2023-11-08 16:21:10.095783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc0f131048c'
down_revision: Union[str, None] = '16c26a925644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_transactions', sa.Column('chainId', sa.String(), nullable=True))
    op.add_column('sybil_clusters', sa.Column('chainId', sa.String(), nullable=True))
    op.add_column('transfers', sa.Column('chainId', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'chainId')
    op.drop_column('sybil_clusters', 'chainId')
    op.drop_column('contract_transactions', 'chainId')
    # ### end Alembic commands ###
