"""add gas price to transfer table

Revision ID: efe07de18038
Revises: 4b51287a0242
Create Date: 2023-09-20 11:04:37.448215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe07de18038'
down_revision: Union[str, None] = '4b51287a0242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('gas_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'gas_price')
    # ### end Alembic commands ###
