"""updated transfer table with processed column

Revision ID: fa552a2a6b8e
Revises: 3f0ce6dc134f
Create Date: 2023-10-12 16:24:53.067803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa552a2a6b8e'
down_revision: Union[str, None] = '3f0ce6dc134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'processed')
    # ### end Alembic commands ###
